DATASETS_PATH : "../dataset/"
REPORT_PATH : "../reports/"
PLOTS_PATH : "../plots/"
ANALYSIS_PATH : "../analysis/"
INFO_PATH : "info/"
MODELS_PATH : "models/"
INTERIM_PATH : "interim/"
FEATURES_PATH : "features/"


DATASETS : [
    "concatenated-dataset",
    "albert-einstein",
    "beneficencia-portuguesa",
    "hospital-de-clinicas",
    "sirio-libanes",
    "grupo-fleury"
    ]
MODELS : [
    "Decision Tree" ,
    "Random Forest" ,
    # "KNN" ,
    # "Logistic Regression" ,
    # "SVM"
]

SPARSE_COLUMN : 75
SPARSE_ROW : 75
N_FOLDS : 10
N_FEATURES : 10
N_FEATURES_THRESHOLD: 15
N_FEATURES_BEST_THRESHOLD: 20
FS_THRESHOLD : 0.25