DATASETS_PATH : "../dataset/"
REPORT_PATH : "../reports/"
PLOTS_PATH : "../plots/"
ANALYSIS_PATH : "../analysis/"
INFO_PATH : "info/"
MODELS_PATH : "models/"
INTERIM_PATH : "interim/"
FEATURES_PATH : "features/"


DATASETS : [
    "concatenated-dataset",
    "albert-einstein",
    "beneficencia-portuguesa",
    "hospital-de-clinicas",
    "sirio-libanes",
    "grupo-fleury"
    ]
MODELS : [
    "Decision Tree" ,
    "Random Forest" ,
    "KNN" ,
    "Logistic Regression" ,
    "SVM"
]
FS_MODELS : [
    "f_classif",
    # ANOVA F-value between label/feature for classification tasks.
    "mutual_info_classif",
    # Mutual information for a discrete target.
    "chi2",
    # Chi-squared stats of non-negative features for classification tasks.
    "SelectPercentile",
    # Select features based on percentile of the highest scores.
    "SelectFpr",
    # Select features based on a false positive rate test.
    "SelectFdr",
    # Select features based on an estimated false discovery rate.
    "SelectFwe",
    # Select features based on family-wise error rate.
    "GenericUnivariateSelect"
    # Univariate feature selector with configurable mode.
]
LEN_FEATURES : 87
SPARSE_COLUMN : 75
SPARSE_ROW : 75
N_FOLDS : 10
N_FEATURES : 100
N_FEATURES_THRESHOLD: 30
N_FEATURES_BEST_THRESHOLD: 20
FS_THRESHOLD : 0.25